transcription/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .signals import delete_folder
delete_folder()

urlpatterns = [
    path('', views.index, name='index'),
    path('video-editing/', views.index2, name='index2'),
    path('uploads/', views.upload_file, name='upload_file'),
    path('api/transcribe/', views.transcribe, name='transcribe'),
    path('api/upload/', views.upload_file, name='upload'),
    path('api/get/', views.get_file, name='get_file'),
    path('api/cut/', views.cut_file, name='cut_file'),
    path('api/cuts/', views.cut_files, name='cut_files'),
    path('api/delete/', views.delete_file, name='delete_file'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transcriptsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('transcription.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

transcription/models.py
from django.db import models
from django.utils.timezone import now


class Video(models.Model):

    # Date image was added
    date = models.DateTimeField("date updated", auto_now_add=True)

    # Video field containing uploaded video
    video = models.FileField(upload_to="uploads")

transcription/forms.py
from django import forms
from .models import Video


class UploadVideoForm(forms.ModelForm):
    
    class Meta:
        model = Video
        fields = ['video']

transcription/views.py
import uuid
import json

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.core.files.base import ContentFile
from .forms import UploadVideoForm
from .models import Video

import whisper_timestamped as whisper
import moviepy.editor

SMALL = 0.1  # Number of seconds for two cuts to count as one

# Load a model:

model = whisper.load_model("base")


def merge_times(times):
    """
    Merges a list of times.

    The idea is to convert two cuts with a small
    time diff into one cut to avoid awkward cuts.

    :param times: List of times
    :type times: List[Tuple(int, int)]
    """

    final = []
    last = [0, 0]
    index = -1

    # Iterate over all times:

    while index < len(times) - 1:

        # Determine if we need to merge

        if times[index+1][0] - last[1] < SMALL:

            # Set last:

            last = [last[0], times[index+1][1]]

        # Otherwise, just set last:

        else:

            # Determine if we should add to final:

            if last[0] != last[1]:

                # Add value to final:

                final.append(last)

            # Set last:

            last = times[index+1]

        # Increment index:

        index += 1

    # Finally, add last to list:

    final.append(last)

    return final


def index(request):
    return render(request, 'Frontend/Home.html')


def index2(request):
    return render(request, 'Frontend/video-editing.html')


def upload_file(request):

    if request.method == 'POST':

        print("In POST")

        # Create a form from the given request:

        print("Request: {}".format(request))
        print(request.POST)
        print(request.FILES)

        form = UploadVideoForm(request.POST, request.FILES)

        # Ensure it is valid:

        if form.is_valid():

            print("Is Valid")

            # Form is valid, save:

            model = form.save()

            print(model.video.path)

            # Next, return the ID to the user:

            return JsonResponse({'video-id': model.id})


def transcribe(request):

    if request.method == 'POST':

        # Determine in ID:

        id = request.POST['id']

        # Grab the file in question:

        video = Video.objects.filter(id=id)[0]

        # Now, transcode the file:

        audio = whisper.load_audio(video.video.path)

        result = whisper.transcribe(model, audio)

        output = {"timestamps": []}

        for seg in result['segments']:

            # Determine the text spoken:

            text = seg['text']

            # Determine the time this segment started at:

            start = seg['start']

            # Next, get the words:

            words = seg['words']

            # Save the data to a final dictionary:

            output['timestamps'].append({'text': text, 'start_time': start, 'words': words})

        return JsonResponse(output)


def get_file(request):

    if request.method == 'POST':

        # Determine the ID:

        id = request.POST['id']

        # Grab the file:

        video = Video.objects.filter(id=id)[0]

        # Return the URL to the file:

        return JsonResponse({'url': video.video.url})


def cut_file(request):

    if request.method == 'POST':

        # Determine the ID:

        id = request.POST['id']

        # Grab the file:

        video = Video.objects.filter(id=id)[0]

        # Get the start and stop time:

        first_time = float(request.POST['start'])
        second_time = float(request.POST['stop'])

        print("First time: {}".format(first_time))
        print("Second time: {}".format(second_time))

        # Create video model and blank file:

        nvideo = Video()
        nvideo.video.save(str(uuid.uuid4()) + '.mp4', ContentFile(''))
        nvideo.save()

        # Create and clip the video:

        clip = moviepy.editor.VideoFileClip(video.video.path)

        # Cut the segment out of the clip:

        nclip = clip.cutout(first_time, second_time)

        # Path to cut video:

        nclip.write_videofile(nvideo.video.path)

        print(nclip.duration)
        print(clip.duration)

        clip.close()
        nclip.close()

        return JsonResponse({'id': nvideo.id})


def cut_files(request):

    if request.method == 'POST':

        # Determine the ID:

        id = request.POST['id']

        # Grab the file:

        video = Video.objects.filter(id=id)[0]

        # Decode the cuts:

        cuts = json.loads(request.POST['cuts'])['timestamps']

        # Sort by start value:

        cuts.sort(key=lambda x: x[0])

        print("Original Cut: {}".format(cuts))

        if len(cuts) >= 2:

            cuts = merge_times(cuts)

        print(cuts)

        # Create video model and blank file:

        nvideo = Video()
        nvideo.video.save(str(uuid.uuid4()) + '.mp4', ContentFile(''))
        nvideo.save()

        # Load the video:

        clip = moviepy.editor.VideoFileClip(video.video.path)

        total_removed = 0

        # Iterate over each cut:

        for cut in cuts:
            print(f"Current timestamp: {cut}")

            # clip = clip.cutout(cut[0] - total_removed, cut[1] - total_removed)

            duration = clip.duration

            first_clip = clip.subclip(0, cut[0] - total_removed)
            second_clip = clip.subclip(cut[1] - total_removed, duration)

            clip = moviepy.editor.concatenate_videoclips([first_clip, second_clip])

            total_removed += cut[1] - cut[0]

        # Save video to memory:

        clip.write_videofile(nvideo.video.path)

        return JsonResponse({'id': nvideo.id})


def delete_file(request):

    if request.method == 'POST':

        # Determine the ID:

        id = request.POST['id']

        # Grab the file:

        video = Video.objects.filter(id=id)[0]

        # Delete the video:

        video.video.delete()

        video.delete()

        return JsonResponse({'deleted': True})

Frontend/templates/Frontend/Home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="icon" type="image/png" href="{% static 'images/Logo-32.png' %}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static 'images/Logo-16.png' %}" sizes="16x16" />

  <link href="{% static 'https://cdn.quilljs.com/1.3.6/quill.snow.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/home.css'%}">
  <title>Transcript-Home</title>
</head>
<body>
  <div id="navbar">
    <nav>
        <img src="{% static 'images/Extended-logo.png'%}" class="logo">
        <ul>
            <li><a href="">About</a></li> 
            <!-- <div class="login">
              <li><a href="" id="login">Login</a></li> 
              <li><a href="" id="login">Sign-up</a></li> 
            </div> -->
            <button>Login</button>
            <button>Sign-up</button>
        </ul>
    </nav>
  </div>


  <div class="camera-container">
    <img src= "{% static 'images/OldSchoolCamera.png' %}" class="camera">
    <img src="{% static 'images/camera-light.png' %}" class="light">
  </div>
  

  <div id="editor-container">

    <div class="text-container">
      <h1>Revolutionizing <br> Video Editing</h1>
      <p>Using the latest AI technology we provide a new and improved way to edit your videos.</p>
      <a href={% url 'index2' %}>Upload your video</a>
    </div>

    <!-- <button id="center-button">Click Me</button> -->
    <div id="editor"></div>
  </div>


  
  <!-- <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
  <script>
    var editor = new Quill('#editor', {
      modules: {
        toolbar: false
      },
      placeholder: false,
      theme: 'snow'
    });
    editor.root.innerHTML = '<p>Using the latest AI technology, we provide an innovative way to edit your videos. </p>';
  </script> -->
</body>
</html>

Frontend/templates/Frontend/video-editing.html
{% load static%}

<html>
  <head>
    <link rel="icon" type="image/png" href="{% static 'images/Logo-32.png' %}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static 'images/Logo-16.png' %}" sizes="16x16" />

    <link rel="stylesheet" href="{% static 'css/video-editing.css' %}"/>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'/>
    <script src="https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js"></script>

    <title>Transcript-Editing</title>
  </head>
  <body>
    
    <div id="wrapper">
      <header>Upload A Video File</header>
      <form action="/uploads/" method ="POST" enctype = "multipart/form-data">
         {% csrf_token %} 
        <input class="file-input" type="file" name="video" id="id_video" hidden>
        <i class="fas fa-cloud-upload-alt"></i>
        <p>Browse File to Upload</p>
      </form>
      <section class="progress-area"></section>
      <section class="uploaded-area"></section>
    </div>
    
    <div id="loading-container">
      <div class="bar">
          <div class="fill"></div>
      </div>
      <p>Loading your workspace...</p>
    </div>


    <!-- Transcript Container -->
    <div id="editor-container">
      
      

      <div id="navbar">
        <nav>
            <ul>
            </ul>
        </nav>
      </div>

      <div class="transcript-container-wrapper">

          <div class="transcript-controls">
              <button id="edit-transcript", onclick="editTranscript()">Edit</button>
              <button id="download-transcript", onclick="downloadTranscript()">Download</button>
              <button id="save-transcript", onclick="saveTranscript()">Save</button>
              <button id="delete-transcript", onclick="deleteTranscript()">Delete</button> 
          </div>

          <div class="transcript-container">
              <div class="transcript-header">
                  <p></p>
              </div>

              <!-- Transcript -->
              <div id = "transcript">

              </div> 
          </div>

      </div>

      <!-- Video -->

          
      <div class="video-container">

          <video id="video" controls>
              <source id="source" type="video/mp4">
          </video>

          <div id="timeline">
              <div id="timeline-controls">
                <button id="cut" onclick="cuttingMode()">cut</button>
                <button id="start" onclick="startCut()">start</button>
                <button id="end" onclick="endCut()">end</button>
              </div> 
              <div id="screenshotContainer">
                  <div id="bar"></div>
              </div>
          </div>

      </div> 
      <script src="{% static 'js/upload-video.js' %}"></script>
      <script src="{% static 'js/transcript-generation.js' %}"></script>
      <script src="{% static 'js/transcript-editing.js' %}"></script>
      <script src="{% static 'js/video-editing.js' %}"></script>
      <script src="{% static 'js/generate-timeline.js' %}"></script>
      <script>       
          document.addEventListener("DOMContentLoaded", function() {
              console.log("----------------DOMContentLoaded------------------------")
          });
    </script>

      

      </body>